# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '4_9_mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1148, 814)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.left_widget = QtWidgets.QWidget(self.centralwidget)
        self.left_widget.setObjectName("left_widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.left_widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.time_bar_widget = QtWidgets.QWidget(self.left_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time_bar_widget.sizePolicy().hasHeightForWidth())
        self.time_bar_widget.setSizePolicy(sizePolicy)
        self.time_bar_widget.setMinimumSize(QtCore.QSize(0, 150))
        self.time_bar_widget.setObjectName("time_bar_widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.time_bar_widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.time_label_widget = QtWidgets.QWidget(self.time_bar_widget)
        self.time_label_widget.setObjectName("time_label_widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.time_label_widget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.time_word_label = QtWidgets.QLabel(self.time_label_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time_word_label.sizePolicy().hasHeightForWidth())
        self.time_word_label.setSizePolicy(sizePolicy)
        self.time_word_label.setMinimumSize(QtCore.QSize(80, 0))
        self.time_word_label.setObjectName("time_word_label")
        self.horizontalLayout_2.addWidget(self.time_word_label)
        self.time_show_label = QtWidgets.QLabel(self.time_label_widget)
        self.time_show_label.setObjectName("time_show_label")
        self.horizontalLayout_2.addWidget(self.time_show_label)
        self.num_p_word_label = QtWidgets.QLabel(self.time_label_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_p_word_label.sizePolicy().hasHeightForWidth())
        self.num_p_word_label.setSizePolicy(sizePolicy)
        self.num_p_word_label.setMinimumSize(QtCore.QSize(100, 0))
        self.num_p_word_label.setObjectName("num_p_word_label")
        self.horizontalLayout_2.addWidget(self.num_p_word_label)
        self.num_p_input = QtWidgets.QLineEdit(self.time_label_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_p_input.sizePolicy().hasHeightForWidth())
        self.num_p_input.setSizePolicy(sizePolicy)
        self.num_p_input.setObjectName("num_p_input")
        self.horizontalLayout_2.addWidget(self.num_p_input)
        self.num_p_button = QtWidgets.QPushButton(self.time_label_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_p_button.sizePolicy().hasHeightForWidth())
        self.num_p_button.setSizePolicy(sizePolicy)
        self.num_p_button.setMinimumSize(QtCore.QSize(100, 0))
        self.num_p_button.setObjectName("num_p_button")
        self.horizontalLayout_2.addWidget(self.num_p_button)
        self.verticalLayout_2.addWidget(self.time_label_widget)
        self.time_slider_widget = QtWidgets.QWidget(self.time_bar_widget)
        self.time_slider_widget.setObjectName("time_slider_widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.time_slider_widget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.time_start_label = QtWidgets.QLabel(self.time_slider_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time_start_label.sizePolicy().hasHeightForWidth())
        self.time_start_label.setSizePolicy(sizePolicy)
        self.time_start_label.setMinimumSize(QtCore.QSize(100, 0))
        self.time_start_label.setObjectName("time_start_label")
        self.horizontalLayout_3.addWidget(self.time_start_label)
        self.time_slider = QtWidgets.QSlider(self.time_slider_widget)
        self.time_slider.setOrientation(QtCore.Qt.Horizontal)
        self.time_slider.setObjectName("time_slider")
        self.horizontalLayout_3.addWidget(self.time_slider)
        self.time_end_label = QtWidgets.QLabel(self.time_slider_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time_end_label.sizePolicy().hasHeightForWidth())
        self.time_end_label.setSizePolicy(sizePolicy)
        self.time_end_label.setMinimumSize(QtCore.QSize(100, 0))
        self.time_end_label.setObjectName("time_end_label")
        self.horizontalLayout_3.addWidget(self.time_end_label)
        self.verticalLayout_2.addWidget(self.time_slider_widget)
        self.verticalLayout.addWidget(self.time_bar_widget)
        self.show_widget = QtWidgets.QWidget(self.left_widget)
        self.show_widget.setObjectName("show_widget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.show_widget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.localization_widget = QtWidgets.QWidget(self.show_widget)
        self.localization_widget.setObjectName("localization_widget")
        self.horizontalLayout_4.addWidget(self.localization_widget)
        self.three_widget = QtWidgets.QWidget(self.show_widget)
        self.three_widget.setObjectName("three_widget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.three_widget)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.phase_widget = QtWidgets.QWidget(self.three_widget)
        self.phase_widget.setObjectName("phase_widget")
        self.verticalLayout_7.addWidget(self.phase_widget)
        self.rss_widget = QtWidgets.QWidget(self.three_widget)
        self.rss_widget.setObjectName("rss_widget")
        self.verticalLayout_7.addWidget(self.rss_widget)
        self.spectrum_widget = QtWidgets.QWidget(self.three_widget)
        self.spectrum_widget.setObjectName("spectrum_widget")
        self.verticalLayout_7.addWidget(self.spectrum_widget)
        self.horizontalLayout_4.addWidget(self.three_widget)
        self.verticalLayout.addWidget(self.show_widget)
        self.horizontalLayout.addWidget(self.left_widget)
        self.right_widget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.right_widget.sizePolicy().hasHeightForWidth())
        self.right_widget.setSizePolicy(sizePolicy)
        self.right_widget.setMinimumSize(QtCore.QSize(300, 0))
        self.right_widget.setObjectName("right_widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.right_widget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.connect_server_widget = QtWidgets.QWidget(self.right_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connect_server_widget.sizePolicy().hasHeightForWidth())
        self.connect_server_widget.setSizePolicy(sizePolicy)
        self.connect_server_widget.setMaximumSize(QtCore.QSize(16777215, 150))
        self.connect_server_widget.setObjectName("connect_server_widget")
        self.formLayout = QtWidgets.QFormLayout(self.connect_server_widget)
        self.formLayout.setObjectName("formLayout")
        self.ip_label = QtWidgets.QLabel(self.connect_server_widget)
        self.ip_label.setObjectName("ip_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.ip_label)
        self.ip_input = QtWidgets.QLineEdit(self.connect_server_widget)
        self.ip_input.setObjectName("ip_input")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ip_input)
        self.admin_label = QtWidgets.QLabel(self.connect_server_widget)
        self.admin_label.setObjectName("admin_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.admin_label)
        self.admin_input = QtWidgets.QLineEdit(self.connect_server_widget)
        self.admin_input.setObjectName("admin_input")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.admin_input)
        self.password_label = QtWidgets.QLabel(self.connect_server_widget)
        self.password_label.setObjectName("password_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.password_label)
        self.password_input = QtWidgets.QLineEdit(self.connect_server_widget)
        self.password_input.setObjectName("password_input")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.password_input)
        self.connect_button = QtWidgets.QPushButton(self.connect_server_widget)
        self.connect_button.setObjectName("connect_button")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.connect_button)
        self.verticalLayout_3.addWidget(self.connect_server_widget)
        self.line = QtWidgets.QFrame(self.right_widget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.load_widget = QtWidgets.QWidget(self.right_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.load_widget.sizePolicy().hasHeightForWidth())
        self.load_widget.setSizePolicy(sizePolicy)
        self.load_widget.setObjectName("load_widget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.load_widget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.file_name_label = QtWidgets.QLabel(self.load_widget)
        self.file_name_label.setObjectName("file_name_label")
        self.verticalLayout_5.addWidget(self.file_name_label)
        self.load_button = QtWidgets.QPushButton(self.load_widget)
        self.load_button.setObjectName("load_button")
        self.verticalLayout_5.addWidget(self.load_button)
        self.verticalLayout_3.addWidget(self.load_widget)
        self.line_3 = QtWidgets.QFrame(self.right_widget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_3.addWidget(self.line_3)
        self.tag_widget = QtWidgets.QWidget(self.right_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tag_widget.sizePolicy().hasHeightForWidth())
        self.tag_widget.setSizePolicy(sizePolicy)
        self.tag_widget.setObjectName("tag_widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tag_widget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tag_label = QtWidgets.QLabel(self.tag_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tag_label.sizePolicy().hasHeightForWidth())
        self.tag_label.setSizePolicy(sizePolicy)
        self.tag_label.setMaximumSize(QtCore.QSize(16777215, 20))
        self.tag_label.setObjectName("tag_label")
        self.verticalLayout_4.addWidget(self.tag_label)
        self.tag_box = QtWidgets.QComboBox(self.tag_widget)
        self.tag_box.setObjectName("tag_box")
        self.verticalLayout_4.addWidget(self.tag_box)
        self.verticalLayout_3.addWidget(self.tag_widget)
        self.line_2 = QtWidgets.QFrame(self.right_widget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_3.addWidget(self.line_2)
        self.ant_widget = QtWidgets.QWidget(self.right_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ant_widget.sizePolicy().hasHeightForWidth())
        self.ant_widget.setSizePolicy(sizePolicy)
        self.ant_widget.setObjectName("ant_widget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.ant_widget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.ant_box = QtWidgets.QGroupBox(self.ant_widget)
        self.ant_box.setObjectName("ant_box")
        self.formLayout_2 = QtWidgets.QFormLayout(self.ant_box)
        self.formLayout_2.setObjectName("formLayout_2")
        self.ant_1 = QtWidgets.QCheckBox(self.ant_box)
        self.ant_1.setObjectName("ant_1")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.ant_1)
        self.ant_2 = QtWidgets.QCheckBox(self.ant_box)
        self.ant_2.setObjectName("ant_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ant_2)
        self.ant_3 = QtWidgets.QCheckBox(self.ant_box)
        self.ant_3.setObjectName("ant_3")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.ant_3)
        self.ant_4 = QtWidgets.QCheckBox(self.ant_box)
        self.ant_4.setObjectName("ant_4")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.ant_4)
        self.ant_5 = QtWidgets.QCheckBox(self.ant_box)
        self.ant_5.setObjectName("ant_5")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.ant_5)
        self.ant_6 = QtWidgets.QCheckBox(self.ant_box)
        self.ant_6.setObjectName("ant_6")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.ant_6)
        self.ant_7 = QtWidgets.QCheckBox(self.ant_box)
        self.ant_7.setObjectName("ant_7")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.ant_7)
        self.ant_8 = QtWidgets.QCheckBox(self.ant_box)
        self.ant_8.setObjectName("ant_8")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.ant_8)
        self.ant_9 = QtWidgets.QCheckBox(self.ant_box)
        self.ant_9.setObjectName("ant_9")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.ant_9)
        self.ant_10 = QtWidgets.QCheckBox(self.ant_box)
        self.ant_10.setObjectName("ant_10")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.ant_10)
        self.ant_11 = QtWidgets.QCheckBox(self.ant_box)
        self.ant_11.setObjectName("ant_11")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.ant_11)
        self.ant_12 = QtWidgets.QCheckBox(self.ant_box)
        self.ant_12.setObjectName("ant_12")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.ant_12)
        self.ant_13 = QtWidgets.QCheckBox(self.ant_box)
        self.ant_13.setObjectName("ant_13")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.ant_13)
        self.ant_14 = QtWidgets.QCheckBox(self.ant_box)
        self.ant_14.setObjectName("ant_14")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.ant_14)
        self.ant_15 = QtWidgets.QCheckBox(self.ant_box)
        self.ant_15.setObjectName("ant_15")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.ant_15)
        self.ant_16 = QtWidgets.QCheckBox(self.ant_box)
        self.ant_16.setObjectName("ant_16")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.ant_16)
        self.verticalLayout_6.addWidget(self.ant_box)
        self.verticalLayout_3.addWidget(self.ant_widget)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.right_widget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.time_word_label.setText(_translate("MainWindow", "Time"))
        self.time_show_label.setText(_translate("MainWindow", "TextLabel"))
        self.num_p_word_label.setText(_translate("MainWindow", "Num of Point"))
        self.num_p_button.setText(_translate("MainWindow", "Set"))
        self.time_start_label.setText(_translate("MainWindow", "Time Start"))
        self.time_end_label.setText(_translate("MainWindow", "Time End"))
        self.ip_label.setText(_translate("MainWindow", "IP"))
        self.admin_label.setText(_translate("MainWindow", "Admin"))
        self.password_label.setText(_translate("MainWindow", "Password"))
        self.connect_button.setText(_translate("MainWindow", "connect"))
        self.file_name_label.setText(_translate("MainWindow", "File Name"))
        self.load_button.setText(_translate("MainWindow", "Load"))
        self.tag_label.setText(_translate("MainWindow", "Tag"))
        self.ant_box.setTitle(_translate("MainWindow", "ANT"))
        self.ant_1.setText(_translate("MainWindow", "ANT01"))
        self.ant_2.setText(_translate("MainWindow", "ANT02"))
        self.ant_3.setText(_translate("MainWindow", "ANT03"))
        self.ant_4.setText(_translate("MainWindow", "ANT04"))
        self.ant_5.setText(_translate("MainWindow", "ANT05"))
        self.ant_6.setText(_translate("MainWindow", "ANT06"))
        self.ant_7.setText(_translate("MainWindow", "ANT07"))
        self.ant_8.setText(_translate("MainWindow", "ANT08"))
        self.ant_9.setText(_translate("MainWindow", "ANT09"))
        self.ant_10.setText(_translate("MainWindow", "ANT10"))
        self.ant_11.setText(_translate("MainWindow", "ANT11"))
        self.ant_12.setText(_translate("MainWindow", "ANT12"))
        self.ant_13.setText(_translate("MainWindow", "ANT13"))
        self.ant_14.setText(_translate("MainWindow", "ANT14"))
        self.ant_15.setText(_translate("MainWindow", "ANT15"))
        self.ant_16.setText(_translate("MainWindow", "ANT16"))


