POST http://localhost:3000/lrt/insert
Content-Type: application/json

{
  "Time": 1,
  "tagid": 1,
  "antid":1,
  "phase": 1,
  "rss": 1,
  "pos": 1
}
##############
##############

POST http://localhost:3000/lrt/insertTable
Content-Type: application/json

{
        "Describe":"req.body.Describe",
        "img": "req.body.img",
        "tableName": "req.body.tableName"
}

#############
#############
GET http://localhost:3000/lrt/

#############
#############
POST http://localhost:3000/lrt/replay
Content-Type: application/json

{
  "table": "2021/6/8 19:55:54"
}

#############
#############
GET http://admin:admin@158.132.255.178:15672/api/exchanges
Content-Type: application/json

